version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    restart: always
    environment:
      - NODE_ENV=production
    networks:
      - fitnest-network

networks:
  fitnest-network:
    driver: bridge 